### PR TITLE
Add support for all the container types

### PR DESCRIPTION
**Pull request by CaitSith2**

### CODE REVIEW

**Comment by azaghal** [comment]
Hello and thanks for the quickly submitted PR - I have incorporated the changes via separate commit, though - mainly to preserve some of the indentation, have the commit signed, and to add a changelog entry.

However, thanks for both reporting the issue/feature request and for spending time in creating the PR (left a small kudo note in commit message for posterity :) ).

**Comment by CaitSith2** [comment]
You missed the infinity-container type in the update.

**Comment by azaghal** [comment]
Ok... Let's double-check that one :)

**Comment by azaghal** [comment]
Would you happen to know any mod with infinity container entities that also has filter capability? Just so I can be aware of something for future testing?

**Comment by CaitSith2** [comment]
https://mods.factorio.com/mod/FilterChests - doesn't actually add any chests, but instead adds filter to every chest type, including the vanilla infinity-chest that is present if you go into editor/creative mode.

**Comment by azaghal** [comment]
Hm... Strange, I didn't notice I was able to set filters on infinity chest with that one, but let me give it one more go with some other mods disabled.

**Comment by azaghal** [comment]
Nevermind that, I've set the mod's `Filter chest mode` option to `Add single chest` while I was testing whether the GUI is shown only for filter-capable chests...

**Comment by azaghal** [comment]
Ok, the proper fix should be in with the 1.1.1 release finally :)

**Pull request closed without merging**
